-- ==============================================================================
-- PROJETO ANIMATIVA - EXTENSÃO DE ADMIN, ENUMS, TABELAS E POLÍTICAS RLS
-- Migration: 20260820_admin_and_features.sql
-- ==============================================================================

-- 1. ENUMS
DO $$ BEGIN
    CREATE TYPE "status_voluntario" AS ENUM ('APROVADO', 'PENDENTE', 'REPROVADO');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "funcao" AS ENUM ('VOLUNTARIO', 'ADMIN', 'COORDENADOR');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "status_usuario" AS ENUM ('ATIVO', 'INATIVO', 'PENDENTE');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE "tipo_parceiro" AS ENUM ('APOIADOR', 'PATROCINADOR', 'PARCEIRO');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. AJUSTES NA TABELA USUARIO
ALTER TABLE IF EXISTS "usuario"
    ADD COLUMN IF NOT EXISTS "role" funcao NOT NULL DEFAULT 'VOLUNTARIO',
    ADD COLUMN IF NOT EXISTS "status" status_usuario NOT NULL DEFAULT 'ATIVO';

-- 3. AJUSTES NA TABELA VOLUNTARIO
ALTER TABLE IF EXISTS "voluntario"
    ADD COLUMN IF NOT EXISTS "status_voluntario" status_voluntario NOT NULL DEFAULT 'PENDENTE',
    ADD COLUMN IF NOT EXISTS "status_aprovacao_voluntario" status_voluntario NOT NULL DEFAULT 'PENDENTE';

-- 4. AJUSTES NA TABELA INICIATIVA
ALTER TABLE IF EXISTS "iniciativa"
    ADD COLUMN IF NOT EXISTS "iniciativa_foto" TEXT,
    ALTER COLUMN "autorizada" SET DEFAULT false;

-- 5. TABELA DE PARCEIROS (parceiro)
CREATE TABLE IF NOT EXISTS "parceiro" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(128),
	"link" TEXT,
	"tipo" tipo_parceiro DEFAULT 'PARCEIRO',
	"foto_parceiro" TEXT,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. TABELA DE FOTOS DA ANIMATIVA (animativa_foto)
CREATE TABLE IF NOT EXISTS "animativa_foto" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"storage_path" TEXT NOT NULL,
	"nome_arquivo" VARCHAR(255) NOT NULL,
	"legenda" VARCHAR(255),
	"categoria" VARCHAR(64) DEFAULT 'geral',
	"ordem" INTEGER DEFAULT 0,
	"destaque" BOOLEAN DEFAULT false,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. FUNÇÃO AUXILIAR PARA CHECAGEM DE ADMIN NO POSTGRESQL (SECURITY DEFINER)
CREATE OR REPLACE FUNCTION is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM usuario
    WHERE auth_user_id = auth.uid()
      AND role = 'ADMIN'
  );
$$;

-- 8. HABILITAR RLS NAS TABELAS
ALTER TABLE IF EXISTS "usuario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "voluntario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "iniciativa" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "evento" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "parceiro" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "animativa_foto" ENABLE ROW LEVEL SECURITY;

-- 9. POLÍTICAS RLS PARA ADMIN

-- parceiro
DROP POLICY IF EXISTS "Leitura pública de parceiros" ON "parceiro";
CREATE POLICY "Leitura pública de parceiros" ON "parceiro"
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin gerencia parceiros" ON "parceiro";
CREATE POLICY "Admin gerencia parceiros" ON "parceiro"
    FOR ALL USING (is_admin());

-- animativa_foto
DROP POLICY IF EXISTS "Leitura pública de fotos da Animativa" ON "animativa_foto";
CREATE POLICY "Leitura pública de fotos da Animativa" ON "animativa_foto"
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin gerencia fotos da Animativa" ON "animativa_foto";
CREATE POLICY "Admin gerencia fotos da Animativa" ON "animativa_foto"
    FOR ALL USING (is_admin());

-- usuario
DROP POLICY IF EXISTS "Admin gerencia todos usuarios" ON "usuario";
CREATE POLICY "Admin gerencia todos usuarios" ON "usuario"
    FOR ALL USING (is_admin());

-- voluntario
DROP POLICY IF EXISTS "Admin gerencia todos voluntarios" ON "voluntario";
CREATE POLICY "Admin gerencia todos voluntarios" ON "voluntario"
    FOR ALL USING (is_admin());

-- iniciativa
DROP POLICY IF EXISTS "Admin gerencia todas iniciativas" ON "iniciativa";
CREATE POLICY "Admin gerencia todas iniciativas" ON "iniciativa"
    FOR ALL USING (is_admin());

-- evento
DROP POLICY IF EXISTS "Admin gerencia todos eventos" ON "evento";
CREATE POLICY "Admin gerencia todos eventos" ON "evento"
    FOR ALL USING (is_admin());
