-- ==============================================================================
-- PROJETO ANIMATIVA - SCHEMA DE BANCO DE DADOS POSTGRESQL / SUPABASE
-- ==============================================================================

-- 1. ENUMS
CREATE TYPE "disponibilidade_variavel" AS ENUM (
	'UMA_MENSAL',
	'TODA_SEMANA',
	'CADA_2_SEMANAS',
	'MAX_2_HORAS',
	'MAX_3_HORAS'
);

CREATE TYPE "status_atuacao" AS ENUM (
	'OK',
	'NAO_OK',
	'NAO_COMPARECEU'
);

CREATE TYPE "status_resultado" AS ENUM (
	'SUPEROU',
	'ATINGIU',
	'EMPATOU',
	'ABAIXO',
	'PIOROU'
);

CREATE TYPE "status_colaboracao" AS ENUM (
	'FORMALIZADA',
	'ANDAMENTO',
	'PARADA',
	'CONCLUIDA'
);

CREATE TYPE "status_evento" AS ENUM (
	'ATIVO',
	'INATIVO',
	'REALIZADO',
	'NAO_REALIZADO'
);

-- 2. TABELA DE USUÁRIO (Vinculada ao Supabase Auth via auth_user_id)
CREATE TABLE IF NOT EXISTS "usuario" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"auth_user_id" UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
	"nome" VARCHAR(128),
	"email" VARCHAR(128) UNIQUE,
	"foto_perfil" VARCHAR(255),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. TABELAS AUXILIARES E INSTITUCIONAIS
CREATE TABLE IF NOT EXISTS "rede_iniciativas" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(128),
	"objetivo" TEXT,
	"area_geografica" VARCHAR(255),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "corporacao" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(128),
	"atividade" VARCHAR(32),
	"impacto" TEXT,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. TABELA DE INICIATIVAS
CREATE TABLE IF NOT EXISTS "iniciativa" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
	"id_usuario" INTEGER REFERENCES "usuario"("id") ON DELETE CASCADE,
	"email" VARCHAR(128) NOT NULL,
	"nome" VARCHAR(255) UNIQUE NOT NULL,
	"setor_sociedade" VARCHAR(255),
	"data_criacao_iniciativa" DATE NOT NULL,
	"cep" VARCHAR(8),
	"rua" VARCHAR(255),
	"numero" VARCHAR(64),
	"complemento" VARCHAR(128),
	"cidade" VARCHAR(128),
	"uf" VARCHAR(64),
	"tel_fixo" VARCHAR(16),
	"tel_celular" VARCHAR(16),
	"formalizacao" BOOLEAN,
	"sede_fisica" BOOLEAN,
	"instagram" VARCHAR(255),
	"facebook" VARCHAR(255),
	"youtube" VARCHAR(255),
	"linkedin" VARCHAR(255),
	"whatsapp" VARCHAR(255),
	"site" VARCHAR(255),
	"nome_rep_legal" VARCHAR(255) NOT NULL,
	"cel_rep_legal" VARCHAR(16) NOT NULL,
	"id_corporacao" INTEGER REFERENCES "corporacao"("id") ON DELETE CASCADE,
	"id_rede_iniciativas" INTEGER REFERENCES "rede_iniciativas"("id") ON DELETE CASCADE,
	"proposito_iniciativa" TEXT,
	"valores_iniciativa" TEXT,
	"impacto_iniciativa" TEXT,
	"criacao_iniciativa" TEXT,
	"ecossistema_iniciativa" TEXT,
	"desafios_iniciativa" TEXT,
	"abundancia_iniciativa" TEXT,
	"contribuicao_esperada" TEXT,
	"atividades_oferecidas" TEXT,
	"habilidades_exigidas" TEXT,
	"oferece_capacitacao" BOOLEAN DEFAULT false,
	"canal_duvidas" BOOLEAN DEFAULT false,
	"voluntariado_corporativo" BOOLEAN DEFAULT false,
	"disponibilidade_variavel" disponibilidade_variavel,
	"regra_politica_partidaria" TEXT,
	"tecnologia_ajudar" TEXT,
	"expectativas" TEXT,
	"autorizada" BOOLEAN DEFAULT true,
	"facilitador" VARCHAR(255),
	"data_cadastro" DATE DEFAULT CURRENT_DATE,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. PESSOAS AUTORIZADAS NA INICIATIVA
CREATE TABLE IF NOT EXISTS "pessoas_autorizadas_iniciativa" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_iniciativa" INTEGER NOT NULL REFERENCES "iniciativa"("id") ON DELETE CASCADE,
	"nome" VARCHAR(255),
	"email" VARCHAR(128),
	"tel_celular" VARCHAR(16),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. DIVISÃO ETÁRIA E DISPONIBILIDADE (TABELAS DE DOMÍNIO)
CREATE TABLE IF NOT EXISTS "divisao_etaria" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"faixa_etaria" VARCHAR(16) UNIQUE,
	"nome_da_fase" VARCHAR(32) UNIQUE,
	"descricao" VARCHAR(128),
	"min" INTEGER,
	"max" INTEGER,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "disponibilidade" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"dia" VARCHAR(16) UNIQUE NOT NULL,
	"descricao" VARCHAR(64) UNIQUE NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 7. TABELA DE VOLUNTÁRIOS (SEPARADA DO USUÁRIO AUTH)
CREATE TABLE IF NOT EXISTS "voluntario" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
	"id_usuario" INTEGER UNIQUE REFERENCES "usuario"("id") ON DELETE CASCADE,
	"email" VARCHAR(128) UNIQUE,
	"nome" VARCHAR(255),
	"data_nascimento" DATE,
	"cep" VARCHAR(8),
	"tel_celular" VARCHAR(16),
	"habilidades" TEXT,
	"exp_profissional" TEXT,
	"exp_voluntariado" TEXT,
	"interessado" TEXT,
	"atividades_interesse" TEXT,
	"soube_iniciativa" TEXT,
	"consentimento" BOOLEAN DEFAULT true,
	"data_cadastro" DATE DEFAULT CURRENT_DATE,
	"disponibilidade_variavel" disponibilidade_variavel,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 8. VOLUNTARIADO E EXECUÇÃO
CREATE TABLE IF NOT EXISTS "voluntariado" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_voluntario" INTEGER NOT NULL REFERENCES "voluntario"("id") ON DELETE CASCADE,
	"id_iniciativa" INTEGER NOT NULL REFERENCES "iniciativa"("id") ON DELETE CASCADE,
	"data_formalizacao" DATE,
	"data_inicio" DATE,
	"area_atuacao" TEXT,
	"atividade_atuacao" TEXT,
	"periodo_atuacao" TEXT,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "execucao_voluntariado" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"id_voluntario" INTEGER NOT NULL REFERENCES "voluntario"("id") ON DELETE CASCADE,
	"id_iniciativa" INTEGER NOT NULL REFERENCES "iniciativa"("id") ON DELETE CASCADE,
	"data_trabalho" DATE,
	"atividade_realizada" TEXT,
	"status_atuacao" STATUS_ATUACAO,
	"status_motivo" TEXT,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. ÁREAS TEMAS E TIPO DE ATUAÇÃO
CREATE TABLE IF NOT EXISTS "areas_temas" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY,
	"nome" VARCHAR(64),
	"descricao" TEXT,
	"acao" TEXT,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "tipo_atuacao" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"tipo_atividade" VARCHAR(128),
	"descricao" TEXT,
	"perfil_sugerido" TEXT,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. COLABORAÇÃO E PLANO DE AÇÃO
CREATE TABLE IF NOT EXISTS "colaboracao" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_iniciativa_entregue" INTEGER REFERENCES "iniciativa"("id") ON DELETE SET NULL,
	"id_iniciativa_recebe" INTEGER REFERENCES "iniciativa"("id") ON DELETE SET NULL,
	"data_evento" DATE,
	"necessidade" TEXT,
	"abundancia" TEXT,
	"objetivo" TEXT,
	"data_formalizacao" DATE,
	"meta_acordada" TEXT,
	"status_colaboracao" STATUS_COLABORACAO,
	"nome_gp_entrega" VARCHAR(255),
	"nome_gp_recebe" VARCHAR(255),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "plano_acao" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"id_colaboracao" INTEGER NOT NULL REFERENCES "colaboracao"("id") ON DELETE CASCADE,
	"etapa" TEXT,
	"data" DATE,
	"responsavel" VARCHAR(255),
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. ECOSSISTEMA E EXPECTATIVA ANUAL
CREATE TABLE IF NOT EXISTS "ecossistema" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(32),
	"importancia" TEXT,
	"impacto" TEXT,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "expectativa_anual" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"ano" SMALLINT,
	"descricao" TEXT,
	"resultado" TEXT,
	"status" status_resultado,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 12. TABELA DE EVENTOS
CREATE TABLE IF NOT EXISTS "evento" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "titulo" TEXT NOT NULL,
    "descricao" TEXT,
    "data_inicio" TIMESTAMPTZ,
    "data_fim" TIMESTAMPTZ,
    "local" TEXT,
    "cidade" TEXT,
    "estado" TEXT,
    "imagem_path" TEXT,
    "tipo" TEXT,
    "inscricao_url" TEXT,
    "provedor" TEXT DEFAULT 'even3',
    "provedor_evento_id" TEXT,
    "status" status_evento NOT NULL DEFAULT 'ATIVO',
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 13. TABELAS DE RELACIONAMENTO
CREATE TABLE IF NOT EXISTS "iniciativa_areas_temas" (
	"id_iniciativa" INTEGER NOT NULL REFERENCES "iniciativa"("id") ON DELETE CASCADE,
	"id_area_tema" INTEGER NOT NULL REFERENCES "areas_temas"("id") ON DELETE CASCADE,
	"created_at" TIMESTAMPTZ DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ DEFAULT NOW(),
	PRIMARY KEY("id_area_tema", "id_iniciativa")
);

CREATE TABLE IF NOT EXISTS "iniciativa_divisao_etaria" (
	"id_iniciativa" INTEGER NOT NULL REFERENCES "iniciativa"("id") ON DELETE CASCADE,
	"id_divisao_etaria" INTEGER NOT NULL REFERENCES "divisao_etaria"("id") ON DELETE CASCADE,
	"created_at" TIMESTAMPTZ DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ DEFAULT NOW(),
	PRIMARY KEY("id_divisao_etaria", "id_iniciativa")
);

CREATE TABLE IF NOT EXISTS "iniciativa_disponibilidade" (
	"id_iniciativa" INTEGER NOT NULL REFERENCES "iniciativa"("id") ON DELETE CASCADE,
	"id_disponibilidade" INTEGER NOT NULL REFERENCES "disponibilidade"("id") ON DELETE CASCADE,
	"created_at" TIMESTAMPTZ DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ DEFAULT NOW(),
	PRIMARY KEY("id_iniciativa", "id_disponibilidade")
);

CREATE TABLE IF NOT EXISTS "voluntario_areas_temas" (
	"id_voluntario" INTEGER NOT NULL REFERENCES "voluntario"("id") ON DELETE CASCADE,
	"id_area_tema" INTEGER NOT NULL REFERENCES "areas_temas"("id") ON DELETE CASCADE,
	"created_at" TIMESTAMPTZ DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ DEFAULT NOW(),
	PRIMARY KEY("id_voluntario", "id_area_tema")
);

CREATE TABLE IF NOT EXISTS "voluntario_disponibilidade" (
	"id_voluntario" INTEGER NOT NULL REFERENCES "voluntario"("id") ON DELETE CASCADE,
	"id_disponibilidade" INTEGER NOT NULL REFERENCES "disponibilidade"("id") ON DELETE CASCADE,
	"created_at" TIMESTAMPTZ DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ DEFAULT NOW(),
	PRIMARY KEY("id_voluntario", "id_disponibilidade")
);

-- ==============================================================================
-- 14. TRIGGER AUTOMÁTICO PARA CRIAÇÃO DE PERFIL DE USUÁRIO NA AUTH
-- ==============================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.usuario (auth_user_id, nome, email, foto_perfil)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'nome', new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    COALESCE(new.raw_user_meta_data->>'avatar_url', new.raw_user_meta_data->>'picture', NULL)
  )
  ON CONFLICT (auth_user_id) DO UPDATE
  SET nome = EXCLUDED.nome,
      email = EXCLUDED.email,
      updated_at = NOW();
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==============================================================================
-- 15. POLÍTICAS DE SEGURANÇA (ROW LEVEL SECURITY - RLS)
-- ==============================================================================
ALTER TABLE public.usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.iniciativa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voluntario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evento ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.areas_temas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.divisao_etaria ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.disponibilidade ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tipo_atuacao ENABLE ROW LEVEL SECURITY;

-- Politicas Usuario
CREATE POLICY "Leitura de perfis de usuarios autenticados" ON public.usuario
  FOR SELECT USING (true);

CREATE POLICY "Usuarios podem atualizar seu proprio perfil" ON public.usuario
  FOR UPDATE USING (auth.uid() = auth_user_id);

CREATE POLICY "Usuarios podem inserir seu proprio perfil" ON public.usuario
  FOR INSERT WITH CHECK (auth.uid() = auth_user_id);

-- Politicas Iniciativa
CREATE POLICY "Leitura pública de iniciativas" ON public.iniciativa
  FOR SELECT USING (true);

CREATE POLICY "Usuarios autenticados podem cadastrar iniciativas" ON public.iniciativa
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Responsaveis podem atualizar suas iniciativas" ON public.iniciativa
  FOR UPDATE USING (
    id_usuario IN (SELECT id FROM public.usuario WHERE auth_user_id = auth.uid())
  );

-- Politicas Voluntario
CREATE POLICY "Leitura publica de voluntarios" ON public.voluntario
  FOR SELECT USING (true);

CREATE POLICY "Usuarios autenticados podem se cadastrar como voluntarios" ON public.voluntario
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Voluntarios podem atualizar seu proprio cadastro" ON public.voluntario
  FOR UPDATE USING (
    id_usuario IN (SELECT id FROM public.usuario WHERE auth_user_id = auth.uid())
  );

-- Politicas Evento e Tabelas de Apoio
CREATE POLICY "Leitura publica de eventos" ON public.evento
  FOR SELECT USING (true);

CREATE POLICY "Leitura publica de areas temas" ON public.areas_temas
  FOR SELECT USING (true);

CREATE POLICY "Leitura publica de divisao etaria" ON public.divisao_etaria
  FOR SELECT USING (true);

CREATE POLICY "Leitura publica de disponibilidade" ON public.disponibilidade
  FOR SELECT USING (true);

CREATE POLICY "Leitura publica de tipos de atuacao" ON public.tipo_atuacao
  FOR SELECT USING (true);
