-- ==============================================================================
-- PROJETO ANIMATIVA - FASE 5: STORAGE (BUCKETS, POLÍTICAS E COLUNAS)
-- Migration: 20260820_storage_buckets.sql
-- ==============================================================================

-- 1. CRIAÇÃO DE BUCKETS NO SUPABASE STORAGE (storage.buckets)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
  ('avatars', 'avatars', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']),
  ('iniciativas', 'iniciativas', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']),
  ('eventos', 'eventos', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']),
  ('animativa', 'animativa', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']),
  ('parceiros', 'parceiros', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml'])
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- 2. POLÍTICAS DE ACESSO PÚBLICO PARA LEITURA (SELECT)
DROP POLICY IF EXISTS "Acesso público de leitura aos avatares" ON storage.objects;
CREATE POLICY "Acesso público de leitura aos avatares"
ON storage.objects FOR SELECT
USING (bucket_id = 'avatars');

DROP POLICY IF EXISTS "Acesso público de leitura às iniciativas" ON storage.objects;
CREATE POLICY "Acesso público de leitura às iniciativas"
ON storage.objects FOR SELECT
USING (bucket_id = 'iniciativas');

DROP POLICY IF EXISTS "Acesso público de leitura aos eventos" ON storage.objects;
CREATE POLICY "Acesso público de leitura aos eventos"
ON storage.objects FOR SELECT
USING (bucket_id = 'eventos');

DROP POLICY IF EXISTS "Acesso público de leitura às fotos animativa" ON storage.objects;
CREATE POLICY "Acesso público de leitura às fotos animativa"
ON storage.objects FOR SELECT
USING (bucket_id = 'animativa');

DROP POLICY IF EXISTS "Acesso público de leitura aos parceiros" ON storage.objects;
CREATE POLICY "Acesso público de leitura aos parceiros"
ON storage.objects FOR SELECT
USING (bucket_id = 'parceiros');

-- 3. POLÍTICAS DE UPLOAD (INSERT)
-- Usuários autenticados podem enviar seu próprio avatar
DROP POLICY IF EXISTS "Upload de avatar por usuário autenticado" ON storage.objects;
CREATE POLICY "Upload de avatar por usuário autenticado"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'avatars');

-- Usuários autenticados podem enviar fotos de iniciativas
DROP POLICY IF EXISTS "Upload de foto de iniciativa por autenticado" ON storage.objects;
CREATE POLICY "Upload de foto de iniciativa por autenticado"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'iniciativas');

-- Usuários autenticados ou admins podem enviar para eventos, animativa e parceiros
DROP POLICY IF EXISTS "Upload de imagens gerais por autenticado" ON storage.objects;
CREATE POLICY "Upload de imagens gerais por autenticado"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id IN ('eventos', 'animativa', 'parceiros'));

-- 4. POLÍTICAS DE ATUALIZAÇÃO E EXCLUSÃO (UPDATE / DELETE)
DROP POLICY IF EXISTS "Atualização de arquivos no storage" ON storage.objects;
CREATE POLICY "Atualização de arquivos no storage"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id IN ('avatars', 'iniciativas', 'eventos', 'animativa', 'parceiros'));

DROP POLICY IF EXISTS "Exclusão de arquivos no storage" ON storage.objects;
CREATE POLICY "Exclusão de arquivos no storage"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id IN ('avatars', 'iniciativas', 'eventos', 'animativa', 'parceiros'));

-- 5. ASSEGURAR COLUNAS NAS TABELAS DO BANCO DE DADOS
ALTER TABLE IF EXISTS "usuario"
  ADD COLUMN IF NOT EXISTS "foto_perfil" TEXT;

ALTER TABLE IF EXISTS "iniciativa"
  ADD COLUMN IF NOT EXISTS "iniciativa_foto" TEXT;

ALTER TABLE IF EXISTS "evento"
  ADD COLUMN IF NOT EXISTS "imagem_path" TEXT;

ALTER TABLE IF EXISTS "parceiro"
  ADD COLUMN IF NOT EXISTS "foto_parceiro" TEXT;

-- Tabela de Fotos da Animativa
CREATE TABLE IF NOT EXISTS "animativa_foto" (
	"id" INTEGER PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"storage_path" TEXT NOT NULL,
	"nome_arquivo" VARCHAR(255) NOT NULL,
	"legenda" VARCHAR(255),
	"categoria" VARCHAR(64) DEFAULT 'galeria',
	"ordem" INTEGER DEFAULT 0,
	"destaque" BOOLEAN DEFAULT false,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
